### ISSUE TITLE
Listener does not register an action (or message) generated through the client

### ISSUE THREAD

**Issue by sinnayman** [twitch-irc/twitch-irc#104]
First of all thank you for this amazing library :)

I can't figure how to listen to an action or a message I send through client.action or client.say. Although the action or message does appear in twitch chat, the listeners never trigger. Listeners trigger normally if action or message is entered through twitch chat.

```javascript
client.addListener('action', function (channel, user, message) {
    console.log(user.username + ': ' + message);
    if (message == 'actiontest') {
		client.say(channel, 'action received');
                // dostuff
    }
});

setInterval(function(){
	client.action('channelname', 'sinnaybot joined');
}, 10000);
```

the console message is never shown, although it triggers normally if i send the action via chat.

**Comment by celluj34** [comment]
It looks like you figured it out, but just so others are aware, you need to set the emitSelf property when instantiating the twitch-irc client.

**Comment by sinnayman** [comment]
yes, I just noticed the configuration option in the Documentation! Thank you very much for your reply!
