### ISSUE TITLE
Can't whisper.

### ISSUE THREAD

**Issue by johnRivs** [twitch-irc/twitch-irc#108]
I'm trying to do `ircClient.say(channel, '/w username message');` but it doesn't work.

**Comment by AlcaDesign** [comment]
Whispering is not part of the IRC portion of the chat. You cannot yet send/receive "whisper" with this module.

**Comment by johnRivs** [comment]
Oh ok. Hope it gets implemented soon. It was a very nice addition to the regular Twitch chat.
