### ISSUE TITLE
isMod no longer functioning/no mod special tags?

### ISSUE THREAD

**Issue by casefc3s** [twitch-irc/twitch-irc#109]
Hey, I'm very much a general newbie when it comes to all of this... Twitch bots, node, even Js in this usage. I noticed there were a few changes to Twitch with v3, and that there were updates on the twitch-irc codebase to reflect that (I think the npm package isn't up to date, btw). 

However, I have some code that requires mod permissions to utilize, and I can no longer tell if someone has those perms via .isMod or from their special tags. Is there a workaround for this, or a fix in the works? I don't know the Twitch API itself well enough to create my own temp fix, I've only used this module since I started work on the bot.

Samples of code I used was:
```javascript
// for marking user status in logs
if (user != null) {
	//console.log(user.special); <-- this still shows broadcaster/sub but not mod
	if (user.special.indexOf('broadcaster') >= 0) {
		prefix += "*";
	} if (user.special.indexOf('mod') >= 0) {
		prefix += "@";
	} if (user.special.indexOf('subscriber') >= 0) {
		prefix += "+";
	} if (user.special.indexOf('staff') >= 0) {
		prefix += "=";
	} if (user.special.indexOf('global_mod') >= 0) {
		prefix += "~";
	} if (user.special.indexOf('admin') >= 0) {
		prefix += "^";
	}
}
```

and

```javascript
var msg = message.toLowerCase().split(" ");

// blacklisting command for banlist
if (msg[0] === '!blacklist' && client.isMod(channel, user.username) && msg.length > 1) {
	db.insert('blacklist', {word: msg[1]}).then(function() {
		console.log("Added " + msg[1] + " to blacklisted words/links.");
		client.say(channel, "Added " + msg[1] + " to blacklisted words/links.");
	});
} else if ((msg[0] === '!greylist' || msg[0] === '!graylist') &&
	client.isMod(channel, user.username) && msg.length > 1) {
	// greylisting command for timeout
	db.insert('greylist', {word: msg[1]}).then(function() {
		console.log("Added " + msg[1] + " to greylisted words/links.");
		client.say(channel, "Added " + msg[1] + " to greylisted words/links.");
	});
}
```

**Comment by AlcaDesign** [comment]
When this happened, I changed my code to use this to check mod status:

```javascript
client.addListener('chat', function(channel, user, text, emitSelf) {
    var isMod = user['user-type'] == 'mod' || client.isMod(channel, name);
});
```

---

You should refer to this for the future of Schmoopiie's Twitch TMI module: https://github.com/Schmoopiie/tmi.js/issues/1 This will essentially be the replacement for this module because of the changes at Twitch and the availability of websocket servers at Twitch.

**Comment by casefc3s** [comment]
Thanks a ton! I will keep an eye on the TMI module as well, thank you for the heads up there too. :)
