### ISSUE TITLE
'mod' no longer included in user.special

### ISSUE THREAD

**Issue by johnRivs** [twitch-irc/twitch-irc#114]
Using twitch-irc ^1.2.5.

Apparently, the special key in the user object doesn't show if the user is a mod. It still shows things like subscriber, turbo, broadcaster...

Is that intended? Is it Twitch' fault?

**Comment by AlcaDesign** [comment]
https://github.com/twitch-irc/twitch-irc/issues/109#issuecomment-114683285

**Comment by johnRivs** [comment]
I tried using your `var isMod = user['user-type'] == 'mod' || client.isMod(channel, name);` (assuming `name` is user.username). Doesn't work :/

**Comment by celluj34** [comment]
Make sure you're using tmi.js. Twitch has made changes to the api and this library will probably not work without further changes.

**Comment by johnRivs** [comment]
Oh, I thought tmi.js was a work in progress. Is it ready to use? Does it work as a drop-in replacement?

**Comment by celluj34** [comment]
It is a work in progress, but it does work and requires almost no changes.
There's a small guide on the changes in the repo.
