### ISSUE TITLE
Read this if your module is breaking.

### ISSUE THREAD

**Issue by Schmoopiie** [twitch-irc/twitch-irc#47]
### Explanation of why it is breaking lately

At this time, Twitch is making a LOT of changes to the chat lately and it is breaking the stable version of twitch-irc. The module catches all messages sent to the channels you join and when JTV or TwitchNotify send a message, it fires an event that you will catch on your end. When Twitch decides to change the syntax of those messages, the events won't fire anymore.

A good example would be the new sub anniversary (which is added as an event in the beta) and the new /mods message. Last week, if you were using /mods in a channel, the message returned was ``The moderators of this room are:``, now it is ``The moderators of this channel are:`` which is different and cause the client to not read the mods when you use this command.

### So, the stable version is breaking, what now ?

Keep in mind that I work 50-60 hours a week, I'm doing my best to release a new version soon. I wanted to wait for Twitch to release IRCv3 tags before releasing the new stable version but I will have no choice now to release it ASAP as they are making way to much changes lately and fixing these bugs is a priority because the module is used by many applications (bots and notifiers) which are also used by a lot of broadcasters.

For now I recommend to use the beta version, which may cause some issues but it is still working. I highly recommend to create an issue on Github if you have any problems with it, so we can fix it as soon as possible before the stable release. Make sure your issue wasn't posted before to prevent duplicates.

Thank you! :smile:

**Comment by enilsen16** [comment]
:+1: Thank you for all your help lately. The more I learn about Twitch Client and IRC in general, I'll keep trying to contribute. :smiley:

**Comment by Schmoopiie** [comment]
I appreciate your contributions to the module @enilsen16 :smile:
