### ISSUE TITLE
isMod: Channel name must have # prefix 

### ISSUE THREAD

**Issue by Dr-Evans** [twitch-irc/twitch-irc#52]
In client.js the self.moderators object saves each moderator list with "#channel" as the key. Therefore, passing a channel without # into isMod causes an error. 

Perhaps the channels name in the self.moderator object should be remHash'ed first before adding them to the object? Or maybe add the hash if it is not present in the inputted channel name?

**Comment by Schmoopiie** [comment]
Hey @Dr-Evans, I will add a ``addhash`` to the channel name when adding or removing an element in self,moderators just to make sure it doesn't add a channel without hashtag. Did you notice any bugs related to this ? I just did a console.log() of each events altering self.moderators and they all have a hashtag prepending the channel name, so I guess it still work but I will add the check anyways.

Thanks and nicely spotted :+1:

**Comment by Schmoopiie** [comment]
Updated in the new version of the module, thanks!

**Comment by Dr-Evans** [comment]
Sweet stuff!! :+1:
