### ISSUE TITLE
Join Messages Never Show

### ISSUE THREAD

**Issue by YourRuler** [twitch-irc/twitch-irc#54]
Not sure if I'm doing something wrong or if it's a known issue,
but I am not receiving and Join or part messages from twitch. If I connect to twitch IRC via something like HexChat, I can see them but here I do not. I am logging all messages pre-parsing so I know that it is not a parsing issue.
on('join',function(){}); does not work

**Comment by Schmoopiie** [comment]
In your configuration, change ``tc`` to 1 (http://www.schmoopiie.com/docs/twitch-irc/Configuration)

Changing your TWITCHCLIENT will change the way you receive responses from Twitch. Using 1 will allow you to see JOINs and PARTs (in batch every 30secs - 1min) but you won't be able to listen to certain events from Twitch, such as the [hosting event](http://www.schmoopiie.com/docs/twitch-irc/Events/Hosting), for example. Please note that TWITCHCLIENT will be deprecated in the future, so we don't recommend to create your apps using this unless you really don't have a choice.

**Comment by YourRuler** [comment]
Thanks for this, Is there going to be a way to detect who is connected to the IRC in the future or will we lose out on that feature once it is deprecated?

**Comment by enilsen16** [comment]
@YourRuler depending on your use case the api might help. 

`https://tmi.twitch.tv/group/user/lirik/chatters`

its been known for awhile that TWITCHCLIENT will be eventually depreciated.
