### ISSUE TITLE
Twitch will be upgrading their chat servers, IPs will change.

### ISSUE THREAD

**Issue by Schmoopiie** [twitch-irc/twitch-irc#55]
If your app cannot connect to IRC, try using irc.twitch.tv or use a specific IP address. We will be upgrading the module with the full list of new IPs in the next days.

If you wish to connect to a specific IP address, change your ``preferredServer`` and ``preferredPort`` settings. Documentation for the configuration is available [here](http://www.schmoopiie.com/docs/twitch-irc/Configuration).

Source: http://discuss.dev.twitch.tv/t/upgrading-chat-servers-new-ips/1836

**Comment by Schmoopiie** [comment]
**Main cluster**

Adding:
- 192.16.64.152
- 192.16.64.145
- 192.16.64.144
- 192.16.64.11
Removing:
- 199.9.253.165
- 199.9.249.252
- 199.9.249.253
- 199.9.252.120

**Event cluster**

Adding:
- 192.16.64.150
- 192.16.64.143
Removing:
- 199.9.252.26
- 199.9.251.213

Source: http://discuss.dev.twitch.tv/t/upgrading-chat-servers-new-ips/1836/9

**Comment by xingped** [comment]
Is this why I'm getting "error: Network is unreachable"?

**Comment by celluj34** [comment]
Do we have to wait for another release for this to be updated? How would we work around this in the meantime?

**Comment by enilsen16** [comment]
you need to create a connections object like so-

```
connection: {
      preferredServer: 
      preferredPort:
}
```

From what I read on the forum post you can use the api to get your particular chat server.
`https://api.twitch.tv/api/channels/night/chat_properties`

**Comment by xingped** [comment]
Even using a server/port from that list and the above/docs connection object doesn't solve my issue.

**Comment by enilsen16** [comment]
What channel are you trying to connect to? I don't think you can just pick a random chat server...

**Comment by xingped** [comment]
I'm trying to connect to my own channel. I'll run through the list of servers and see if I can find one that works then if that's the case.

**Comment by enilsen16** [comment]
Hmmm...
I just polled the api with my channel name. Set `preferredServer` and `preferredPort` to the first IP listed. I joined just fine.

```
var client = new irc.client({
  options: {
    debug: true,
    debugDetails: true,
    debugIgnore: [ "ping", "chat"],
    logging: false,
    chat: true,
  },
  connection: {
    preferredServer: '192.16.64.145',
    preferredPort:'80'
  },
  identity: {
    username: process.env.USERNAME,
    password: process.env.OATH_TOKEN,
  },
  channels: 'eyeswl',
});

client.connect();
```

```
[21:16:32] event - connecting
[21:16:32] event - logon
[21:16:32] raw   - 001: Welcome, GLHF!
[21:16:32] raw   - 002: Your host is tmi.twitch.tv
[21:16:32] raw   - 003: This server is rather new
[21:16:32] raw   - 004: -
[21:16:32] raw   - 375: -
[21:16:32] raw   - 372: You are in a maze of twisty passages, all alike.
[21:16:32] event - connected
[21:16:32] raw   - 376: >
[21:16:35] event - join
[21:16:35] raw   - 366: #eyeswl
```

**Comment by xingped** [comment]
Sorry about that, apparently my VM's network bridge shat itself. Thanks for confirming it is indeed working!

**Comment by Schmoopiie** [comment]
Closing this issue, you may now update the module to the latest version.
