### ISSUE TITLE
Subscription events trigger for hosted channels

### ISSUE THREAD

**Issue by EfficiencyVI** [twitch-irc/twitch-irc#58]
A few weeks agon Twitch added the most useless feature ever. When you host a channel you are informed about subscriptions in the hosted channel. This notifications look slightly different than the usual host notifications.

> username just subscribed to channelname!

and

> username subscribed to channelname x months in a row!

I don't know how you want to solve it, for now I added a third/fourth parameter to the subscription event in the client.js:

```javascript
        var host_subscription = string(message.params[1]).contains('subscribed to');
        switch(true) {
            /* Someone has subscribed to a channel */
            case (string(message.params[1]).contains('just subscribed')):
                self.logger.event('subscription');
                self.emit('subscription', message.params[0], message.params[1].split(' ')[0], host_subscription);
                break;

            /* Someone has shared his sub anniversary */
            case (string(message.params[1]).contains('subscribed') && string(message.params[1]).contains('in a row')):
                var splitted = message.params[1].split(' ');
                var length   = splitted[splitted.length - 5];

                self.logger.event('subanniversary');
                self.emit('subanniversary', message.params[0], splitted[0], length, host_subscription);
                break;
        }
```

With the additional parameter I can intercept host subscriptions and stop them from being triggered. But maybe you want to add another event for that, I don't know.

**Comment by Schmoopiie** [comment]
I am aware of this feature, if you can think of a name for this event I will add it for sure. I just don't want to mess with the actual events because the module is being used by large applications (bots and notifiers)

**Comment by EfficiencyVI** [comment]
That's why I didn't add anything to the code. This issue is just a reminder to fix it because right now the host subscriptions are triggered like an actual event in your channel and this is definitely wrong. I hoped it was a bug on Twitch but I think they want to keep it for unknown reasons. :-D

**Comment by Schmoopiie** [comment]
Ohh gotcha :smile:

**Comment by Schmoopiie** [comment]
Fixed, thanks!
