### ISSUE TITLE
Bot stops sending messages

### ISSUE THREAD

**Issue by EfficiencyVI** [twitch-irc/twitch-irc#59]
After a short amount of time messages from our bot does not go into chat.

```javascript
var client = new irc.client({
    options: {
        debug: true,
        debugIgnore: ['ping'],
        logging: false,
        tc: 1
    },
    identity: {
        username: 'DolphinBot23',
        password: 'oauth:xxxx'
    },
    channels: [channel]
});
```

the connection is established and he can send messages, after a few seconds (maybe 30) the connection is still there but the bot doesn't send any messages. This is urgent.

**Comment by Schmoopiie** [comment]
It doesn't send any messages but does it receive messages ?

**Comment by EfficiencyVI** [comment]
It receives messages. It also answers them but the messages don't go into chat.

**Comment by Schmoopiie** [comment]
I will look onto this right now but I can't promise you any fix if I can't reproduce this error..

**Comment by EfficiencyVI** [comment]
```javascript
client.prototype.say = function(channel, message) {

console.log(channel);
console.log(message);

    var self     = this;
    var deferred = q.defer();
    // Socket isn't null and channel has been joined..
    if (self.socket !== null && self.currentChannels.indexOf(utils.remHash(channel).toLowerCase()) >= 0) {
        self.socket.crlfWrite('PRIVMSG ' + utils.addHash(channel).toLowerCase() + ' :' + message);
        deferred.resolve(true);
    } else { deferred.resolve(false); }

    return deferred.promise;
};
```
when I add that, the messages and the right channel are displayed in the output. But the never make it into chat. I haven't change anything to our bot.

**Comment by Schmoopiie** [comment]
This is so strange.. everything is fine on my end with a bot using TC1 and another one with IRCv3 tags.. what if you add ``console.log(err);`` right after [this line](https://github.com/twitch-irc/twitch-irc/blob/master/libraries/socket.js#L73) ? Also, did you try with another server ? maybe one of the new Twitch chat server is eating the messages ?

**Comment by EfficiencyVI** [comment]
I think it is a problem with this. I connect to two channels, but in self.currentChannels there is only the second channel.

**Comment by Schmoopiie** [comment]
Can you replace the content of client.js with this and tell me if it works ? https://gist.github.com/Schmoopiie/a0fb13cc22256255d894

**Comment by EfficiencyVI** [comment]
Bot just restarted with your file

**Comment by Schmoopiie** [comment]
Come in http://www.twitch.tv/schmoopiie/

**Comment by EfficiencyVI** [comment]
I can't our stream is running but it seems to be fine so far. :-)

Our channel is http://www.twitch.tv/laurenevans23

**Comment by Schmoopiie** [comment]
Alright, let it run 5 minutes and keep me updated

**Comment by EfficiencyVI** [comment]
Yepp, it works really fine. Was it a bug in your library? We will send you some hearts in our chat. :-)

**Comment by Schmoopiie** [comment]
Yes it was a problem related to TWITCHCLIENT 1.. the way the library works is that it is initializing the internal variables when the bot joins a channel, but TC1 makes it trigger the join event multiple times for that channel so I had to make it [check if it's the bot joining and not someone else](https://gist.github.com/Schmoopiie/a0fb13cc22256255d894#file-test-js-L357).

**Comment by EfficiencyVI** [comment]
It works now. Our chat has 100+ people and I'm the only mod, so I need a bot on my side. ;-)

**Comment by Schmoopiie** [comment]
Yeah, I am on the channel :smile: I will bump the version again I guess.. 3 version bump this morning -_-

**Comment by EfficiencyVI** [comment]
Thank you for fixing it so fast. <3

**Comment by Schmoopiie** [comment]
My pleasure ;-)
