### ISSUE TITLE
App keeps searching for twitch server

### ISSUE THREAD

**Issue by Jordan4jc** [twitch-irc/twitch-irc#61]
I had no issues before but now I am having an issue with connecting to IRC channels, it just sits there with no other output other than `info  - Searching for a Twitch server..`.

To my knowledge nothing crazy has changed, I just all of a sudden cannot get it to connect to a server.

I also tried just copying the basic code to make it work from the documentation but I can't connect with that either

```
var irc = require('twitch-irc');

var clientOptions = {
    options: {
        debug: true,
        debugIgnore: ['ping', 'chat', 'action']
    },
    identity: {
        username: 'mini_tax',
        password: '***'
    },
    channels: ['matax91']
}
var client = new irc.client(clientOptions);

client.connect();

client.addListener('chat', function (channel, user, message) {
    console.log(user.username + ': ' + message);
});
```

**Comment by enilsen16** [comment]
What version of the package are you using? Twitch just updated all the IPs of their servers.

**Comment by Jordan4jc** [comment]
Updated and it's connected, does this happen often? And if so do you have a good solution for always keeping the package up to date other than just remembering to run npm update before running the app?

**Comment by enilsen16** [comment]
We normally update the package as we need too. In the past I think @Schmoopiie has implemented a way to check for updates. I recommend for now periodically running `npm outdated`.
