### ISSUE TITLE
Not getting joins and parts from event listeners

### ISSUE THREAD

**Issue by Jordan4jc** [twitch-irc/twitch-irc#62]
When my bot joins a channel I get an initial join that works but any joins and parts after that don't work, chat events are working.

```
client.addListener('join', function (channel, user) {
  console.log(user+' has joined');
  twitchApi.call({
    channel: null,
    method: 'GET',
    path: '/users/'+user+'/follows/channels/***'
  }, function(err, status, res) {
    if (err) {
      console.log(err);
      return;
    }
    console.log(status);
    console.log(JSON.stringify(res));
  });
});
```

Which returns a 404, which it should since my bot is not following the channel I'm connected to, but after that I'm only getting chat messages and no joins or parts after that.

**Comment by enilsen16** [comment]
If you're trying to get user joins, you may find #54 helpful.

**Comment by Jordan4jc** [comment]
Thanks, that helped.
