### ISSUE TITLE
Sometimes seeing duplicate badges (user.special)

### ISSUE THREAD

**Issue by celluj34** [twitch-irc/twitch-irc#63]
Intermittently I'm seeing duplicate user badges (mod, turbo, etc), but I only ever see it on "myself". Here's an image http://i.imgur.com/i6DWGzH.png. I noticed it's not limited to sub icons, I've seen it with the mod icon too. The most I've seen is 3.

For now I'll use underscore to remove duplicates.

**Comment by Schmoopiie** [comment]
Sorry for the delayed answer, I am on vacation.. Will see what's going on, expect an update next week.

**Comment by celluj34** [comment]
One thing to note, it does sort itself out after a few minutes. When I saw 3 moderator badges, it went to 2, then later it was down to one (I am a mod on that channel).
