### ISSUE TITLE
Is there a way to get the list of users in a channel upon the join action

### ISSUE THREAD

**Issue by Jordan4jc** [twitch-irc/twitch-irc#66]
Just wondering if there is a way to get the list of users when the bot joins, or at any given time?

**Comment by celluj34** [comment]
@Jordan4jc the easiest way is to access the following url: http://tmi.twitch.tv/group/user/<channel>/chatters

**Comment by Schmoopiie** [comment]
That is correct, and if you need an example: http://www.schmoopiie.com/docs/twitch-irc/Examples/Query%20Twitch%20Internal%20API
