### ISSUE TITLE
Not understanding the cron jobs thing

### ISSUE THREAD

**Issue by Jordan4jc** [twitch-irc/twitch-irc#68]
I don't really understand how I can set the job to run every minute, or ten minutes, or hour, the example on the docs just shows how to make it run every second for 10 seconds and then that's it.

**Comment by Schmoopiie** [comment]
There is no documentation because it is a standard Unix cron job, there are tons of tutorials if you search on Google. There is also a [wiki](http://en.wikipedia.org/wiki/Cron) page about it.

To run it every 10 minutes, you can use ``0 */10 * * * *`` or ``*/10 * * * *``.

**Comment by Jordan4jc** [comment]
Okay, didn't realize cron had a standard API, I've literally never used them before. Thanks
