### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by formula1** [twitch-irc/twitch-irc#69]
So from what I understand

### Events

* **crash** (message,stack)- when there has been an uncaught exception anywhere in the node process

#### Connection Specific

* **ping** ()- After recieving PING from twitch. Will send PONG as well
* **pong** (latency)- after recieving PONG from twitch
* **connected** (remoteAddress, remotePort)- after the Bot has been connected
* **disconnected** (reason)- after the Bot has been disconnected
* **logon** () - Emitted before the logon has been done

#### Channel Specific

* **hosting** (channel, targetCHannel, -1?) - When successfully hosted a person
* **unhost** (channelname, targetchannel)- When a channel is no longer hosting another
* **hosted** (channelname,hoster channel,viewers)- When someone else has hosted you
* **mods**(channelname, mods array)- The mods in the room
* **names** (channelname?, names)- recieves current viewers
* **timeout** (channelname?, username?)- after a person has been timed out
* **clearchat** (channelname)- after recieving a clearchat from twitch
* **subscriber** (channelname,true/false) - When the chat is in sub only mode
* **slowmode** (channelname, true/false, period of time)- When the chat has entered slow mode
* **r9kbeta** (channelname, true/false) - When the chat has entered r9k mode

#### User Specific

* **mod** (channelname, nickname?)- When someone has been modded
* **unmod** (channelname, nickname?)- When someone has been unmodded
* **subscription** (channelname, nickname) - When there has been a new subscription
* **subanniversary** (channelname, nickname, length of time) - WHen a user has resubscribed
* **join** (channelname, nickname) - When a user has joined the channel
* **part** (channelname, nickname) - When a user has left the channel
* **action** (channelname, nickname, the action) - When a user has done an action
* **chat** (channelname, nickname, chat) - When a chat message has appeared

### Methods

Almost all methods will return a promise, however, the promise is not asyncronous and will return true/false based on whether or not the connection is connected or not

#### Connection Specific

* **disconnect** () - disconnects from twitch
* **ping** () - pings twitch
* **raw** (message) - sends a raw message to twitch

#### Channel Specific

* **join** (channel) - hosts a channel?
* **part** (channel) - leaves a channel
* **mods** (channel) - gets all mods from the channel
* **clear** (channel) - Clears the channel
* **commercial** (channel, seconds) - runs commercials for X seconds
* **host** (channel, target) - hosts a channel
* **unhost** (channel) - stops hosting a channel
* **r9kbeta** (channel) - sets channel in r9k mode
* **r9kbetaoff** (channel) - the channel will no longer be in r9k mode
* **slow** (channel) - sets channel in slowmode
* **slowoff** (channel) - channel is no longer in slow mode
* **subscribers** (channel)*- sets channel in sub only mode
* **subscribersoff** (channel) - channel is no longer in sub only mode

#### User Specific

* **ban** (channel, nickname) - Bans a user
* **unban** (channel, nickname) - unbans a user
* **timeout** (channel, nickname, seconds) -user is timed out for X Seconds
* **mod** (channel, nickname) - mods a user
* **unmod** (channel, nickname) - user will no longer be a mod
* **isMod** (channel, nickname) - returns boolean if the user is a mod

#### Self

* **say** (channel, message) - Says something
* **action** (channel, message) - Sends text as an action
* **color** (channel, color) - requests to have a different color

**Comment by celluj34** [comment]
There is some documentation available at http://www.schmoopiie.com/docs/twitch-irc/ but I wish it was on the repo that we could make pull requests for.

I think this is helpful, it gives a different view on the events and commands that is always nice.

**Comment by formula1** [comment]
Excellent! I couldn't find the documentation before. I agree though, documentation on the repo would be helpful

**Comment by Schmoopiie** [comment]
Documentation is no longer on GitHub because it is quite limited and it is not mobile friendly. The domain name will change later, but I am not in a hurry to change it. The link is available in the description and also if you click on wiki on GitHub. A link to the [documentation repository](https://github.com/twitch-irc/documentation) is also available and everyone is invited to contribute.
