### ISSUE TITLE
Something has changed? Reconnecting every minute

### ISSUE THREAD

**Issue by Fasani** [twitch-irc/twitch-irc#73]
My project uses this node module and it had stopped working a few weeks back, I have upgraded the module and now I can connect but I seem to get disconnected every 30-60 seconds.

Any one else experiencing this?

I changed preferred port to 443 as I heard 6667 is being blocked sometimes.

    var client = new irc.client({
        options: {
          debug: true,
          debugIgnore: ['ping', 'chat', 'action'],
          logging: false,
          tc: 3
        },
        connection: {
          preferredPort: 443
        },
        identity: {
          username: botUsername,
          password: botAuth
        },
        channels: [channel]
      });

I am auto reconnecting with no issues but then I am being disconnected I know it is a disconnect because of this:

      client.addListener('disconnected', function(reason) {

        $('#connect').show();
        $('#logger').hide();

        myLogger("Disconnected from Twitch!");
      });

And then it reconnects and I am looping between connected and not.

**Comment by Fasani** [comment]
I logged the response message and the reason I get is "Connection timed out."

**Comment by Schmoopiie** [comment]
Hello @Fasani,

I have a few questions for you:

1- Do you see the Logon event when you are connecting to a server ?
2- Are you using the latest node version ?
3- Are you able to run your application on a different server ?
4- What about running a very basic application with the module to see if it connects and stay connected ?

I would like to assist you with your issue, but a connection timeout is really hard to reproduce.

**Comment by Fasani** [comment]
I can start to send bot commands like !song and it responds then a few seconds later it disconnects and then it reconnects and again everything is working.

The entire app is wrapped in NWJS << https://github.com/nwjs << Maybe here there is something causing this issue.

I will try an update node.

It's very odd.

Ty for response. I thought maybe something I was doing had changed in the connection object or something.

**Comment by celluj34** [comment]
@Fasani are you calling the twitch-irc from a file loaded into node-main, or are you calling it directly from the ui-javascript? I ask because I was using nwjs (but switched to atom-shell), but I did not notice any issues like this. I was calling the twitch-irc from my app.js, loaded by node-main.

**Comment by Schmoopiie** [comment]
I have been trying to replicate issue #74 and at the same time I was trying to replicate this issue as well but no success. Perhaps @celluj34's comment will help you figure out what the problem is ?

**Comment by Fasani** [comment]
To confirm this script is causing me the same issue, I am now thinking this is probably a local issue maybe to do with firewall?

Bot connects, I see it in chat... then every 30 seconds it times out and reconnects even with this most basic script.


    process.env['NODE_TLS_REJECT_UNAUTHORIZED'] = '0';

    //Libs
    var irc = require('twitch-irc');

    var client = new irc.client({
      options: {
        debug: false,
        debugIgnore: ['ping', 'chat', 'action']
      },
      identity: {
        username: '##removed##',
        password: '##removed##'
      },
      channels: ['##removed##']
    });

    //Connect to Twitch
    client.connect();

    //Add listeners for connection.
    client.addListener('connecting', function(address, port) {
      myLogger("Connecting...");
    });

    client.addListener('connected', function(address, port) {
      myLogger("Connected!")
    });

    client.addListener('connectfail', function(reason) {
      myLogger("Connection to Twitch failed! " + reason);
    });

    client.addListener('disconnected', function(reason) {
      myLogger("Disconnected from Twitch! " + reason);
    });

    function myLogger(message) {
      console.log(message);
    }

**Comment by Fasani** [comment]
Firewall seems to be allowing traffic fine.. :-(

**Comment by Fasani** [comment]
I set:

        preferredServer: "199.9.251.168",
        preferredPort: "6667",

But in my firewall I still see connection to the default twitch server: 192.16.64.11:80

Any idea why?

**Comment by Fasani** [comment]
I tried with mIRC using 6667, 80, 443 all seems fine and I see the correct port in the firewall.

When I watch the firewall after each timeout twitch-irc reconnects and it uses port 443 and a random ip address from the usual list.

Again after a few minutes I am being timed out.

**Comment by Schmoopiie** [comment]
@Fasani I will provide you with a custom version of twitch-irc this weekend.. I will remove a few features of the module and hopefully we will be able to find what's wrong with it. It's kinda hard to debug the net module of Node.js but I'll do my best to fix your issue.

**Comment by Fasani** [comment]
Quick update, I distributed the app to someone else and they have the same issue as me.

I don't know if it helps but here is my app. It's pretty simple. https://github.com/Fasani/SpottyBot

To run it you either have to drag the entire cloned folder onto the nwjs nw.exe or remove the inline dom / jquery things.

But I have the same issues even with the most basic script that I posted above.

**Comment by Schmoopiie** [comment]
This is what I am doing and I can't replicate your issue.. https://www.youtube.com/watch?v=eGu29XHJIhw .. I am using the latest NWJS and had to comment 2 lines in your code because Spottify isn't available in my country, I also enabled the console. At 7:40 I tried !adminstart just to make sure it is still alive. After uploading the video to youtube, I reconnected SpottyBot and let it run while I was sleeping, just woke up and it is still connected..

**Comment by Fasani** [comment]
Thank you for investigating. This is so strange. I will copy your exact
example and perhaps there is something odd happening. But as I said before
I had the same issue even with just a very basic script. Perhaps it is some
kind of odd DNS issue or network issue.

On 16 April 2015 at 02:02, Schmoopiie <notifications@github.com> wrote:

> This is what I am doing and I can't replicate your issue..
> https://www.youtube.com/watch?v=eGu29XHJIhw .. I am using the latest NWJS
> and had to comment 2 lines in your code because Spottify isn't available in
> my country, I also enabled the console. At 7:40 I tried !adminstart just to
> make sure it is still alive. After uploading the video to youtube, I
> reconnected SpottyBot and let it run while I was sleeping, just woke up and
> it is still connected..
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/twitch-irc/twitch-irc/issues/73#issuecomment-93602301>
> .
>

-- 

Disclaimer: This e-mail message including attachments, if any, is intended 
only for the person(s) or entity to which it is addressed and may contain 
confidential and/or privileged material. Any use of the information 
contained herein (including, but not limited to, total or partial 
reproduction, communication, or dissemination in any form) by persons other 
than the intended recipient(s) is prohibited. If you have received this 
e-mail in error, please notify the sender immediately and delete it.
