### ISSUE TITLE
client.say sending twice

### ISSUE THREAD

**Issue by DigitalKris** [twitch-irc/twitch-irc#74]
I am using NWJS app to run the bot and for some reason 9/10 the bot will send a duplicate message 1 second after the first.

When I say 9/10 (it is probably more than that), this is when the bot connects. If it starts sending a duplicate, it will continue while it is alive. If on the rare occasion it doesn't send out a duplicate message, it doesn't ever seem to until reset.

I'm really not the best at explaining issues lol.

This is the log

```
[17:08:03] event - connecting
[17:08:03] event - logon
[17:08:03] raw   - 001: Welcome, GLHF!
[17:08:03] raw   - 002: Your host is tmi.twitch.tv
[17:08:03] raw   - 003: This server is rather new
[17:08:03] raw   - 004: -
[17:08:03] raw   - 375: -
[17:08:03] raw   - 372: You are in a maze of twisty passages, all alike.
[17:08:03] event - connected
[17:08:03] raw   - 376: >
[17:08:06] event - join
[17:08:06] raw   - 366: #like_a_dot_ninja
[17:08:08] chat  - [#like_a_dot_ninja] like_a_dot_ninja: hello
[17:08:08] chat  - [#like_a_dot_ninja] testbot05830: hello
[17:08:09] chat  - [#like_a_dot_ninja] testbot05830: hello
[17:08:26] chat  - [#like_a_dot_ninja] like_a_dot_ninja: I am being repeated by a damn bot!
[17:08:26] chat  - [#like_a_dot_ninja] testbot05830: I am being repeated by a damn bot!
[17:08:27] chat  - [#like_a_dot_ninja] testbot05830: I am being repeated by a damn bot!
```

The code running is
```javascript
(function(){
	var irc = require('twitch-irc');
	var clientOptions = {
		options: {
			debug : true,
			debugDetails : true
		},
		connection : {
			preferredServer : 'irc.twitch.tv'
		},
		logging : {
			enabled : true,
			chat : true
		},
		identity : {
			username : 'testbot05830',
			password : 'oauth:password'
		},
		channels : ['like_a_dot_ninja']
	}
	var comments = ['hello', 'piece'];
	var client = new irc.client(clientOptions);

	client.connect();

	client.addListener('chat', function(ch, user, msg) {
		if(user.username == clientOptions.identity.username) { return; }
		client.say(ch, msg);
		return;
	});
	client.addListener('disconnected', function (reason) {
		console.log(reason)
	});
	client.addListener('pong', function(l) {
		console.log('pong: ' + l);
	});
	client.addListener('connected', function(a, p) {
		console.log(a, p);
	})
})();
```

**Comment by Schmoopiie** [comment]
I guess I will have to try NWJS this weekend, you're not the first one to report issues with the module while using it with NWJS. Will keep you updated here.

**Comment by Schmoopiie** [comment]
Been trying for a few hours to replicate this but no success.. this is my ``index.html``:

```html
<!DOCTYPE html>
<html>
  <head>
    <title>Hello World!</title>
  </head>
  <body>
    <h1>Hello World!</h1>
    We are using node.js <script>document.write(process.version)</script>.
  </body>
<script>
    (function(){
        var irc = require('twitch-irc');
        ... (this is basically your code but I changed the username and password)
    })();
</script>
</html>
```

When I type something on the channel it is reponding only once. Maybe you are executing the code twice so you have 2 connections ?

Add this listener to your code and make sure you aren't connecting twice to the server using the debug console of your NWJS app.

```javascript
client.addListener('connected', function (address, port) {
    console.log('Connected to ' + address + ':' + port);
});
```

**Comment by DigitalKris** [comment]
I was watching the connected event and only 1 connection was being made 0.o

However, the one slight difference between what you have done and what I done was that my script was a stand alone js file being run by node. (You can achieve this by using node-main in the package.json file). After moving the script into the index file and removing the stand alone js file, it is now working fine.

I honestly never thought about trying that in the first place...

Thank you for spending time trying to figure out the problem and thank you for the overall package!
