### ISSUE TITLE
'chat' listener only catching once or for a very short period of time after connecting to a channel

### ISSUE THREAD

**Issue by xingped** [twitch-irc/twitch-irc#75]
My listener:

    client.addListener('chat', function(channel, user, message) {
        console.log(user.username+' - '+message);
    }

Only fires once or for a very short period of time after connecting to a channel. Even with debug and debugDetails set to true, it's not catching any additional chat events.

I don't know if it has anything to do with it, but my client is within an AngularJS controller. I did not have a problem with this when I used JQuery instead of AngularJS, but that was also a number of months ago so I don't know if it's that or a bug with twitch-irc.

Additional details: using twitch-irc 1.2.5, AngularJS 1.3.1, and Linux Mint 17.1

Edit to add: Apparently twitch-irc will also disconnect and crash after enough time of sitting there idly. The full error log:

error - Error: write after end
    at writeAfterEnd (/home/xingped/Documents/twitchtimer/node_modules/twitch-irc/node_modules/readable-stream/lib/_stream_writable.js:144:12)
    at DestroyableTransform.Writable.write (/home/xingped/Documents/twitchtimer/node_modules/twitch-irc/node_modules/readable-stream/lib/_stream_writable.js:192:5)
    at Socket.ondata (_stream_readable.js:524:20)
    at emitOne (events.js:75:13)
    at Socket.emit (events.js:150:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:109:10)
    at TCP.onread (net.js:510:20)

**Comment by Schmoopiie** [comment]
I never tried to use the module within an AngularJS controller.. If I have enough time, I will give it a try this weekend and I'll try to replicate the issue.

**Comment by xingped** [comment]
Hey, I found the problem (and my example above is overly simplified, and I apologize for that). I was trying to simulate what happens and how I would work with it if a user's credentials were wrong and they changed them. It appears that if I change my credentials and then try to connect without first calling client.disconnect(), I will, in very short order, start experiencing the problems above.

Bad code:

    $scope.$watchGroup(['username','password'], function() {
        client.options.identity = {
            username: $scope.username,
            password: $scope.password
        };
        client.connect();
    });

Good code:

    $scope.$watchGroup(['username','password'], function() {
        client.disconnect();  // <-- Added line
        client.options.identity = {
            username: $scope.username,
            password: $scope.password
        };
        client.connect();
    });

Even though the client is disconnected when I call client.disconnect(), due to previously incorrect credentials, it appears this is necessary before attempting to re-establish a connection with the correct credentials.

**Comment by xingped** [comment]
You can check out my gist here: https://gist.github.com/xingped/5bdb74bd87f4f8b603ed to see a complete example of working/non-working code (add your proper oauth key and then comment out the line specified to break it).

**Comment by Schmoopiie** [comment]
Alright, glad to see you got it working! :smile: :+1:
