### ISSUE TITLE
when using client.emitSelf, action is emitted as chat

### ISSUE THREAD

**Issue by celluj34** [twitch-irc/twitch-irc#76]
like title says, I'm using the emitSelf setting to show chat messages with emotes/color/etc. When I chat an action (e.g., /me test action plz ignore) it comes back as a plain chat message, from the "chat" event.

**Comment by Schmoopiie** [comment]
Yes I know, I still need to work on the logging system, but thanks for pointing that out! :smile:

**Comment by celluj34** [comment]
Actually, I may know what's going on. There's two issues.

The first is, I was sending the action through client.chat instead of client.action. However, twitch chat still interpreted (correctly) it as an action.

The second is as the title suggests, so that may not be an issue.

**Comment by celluj34** [comment]
I have confirmed my earlier findings. It is working as intended, even though Twitch chat interprets it correctly either way. You can close this if you'd like, or (I think I prefer) remove the Action command and handle it internally with the following code:

	socket.on("outgoingMessage", function(data) {
		if(_s.startsWith(data.message, "/me ")) {
			var message = _s.ltrim(data.message, "/me ");

			if(message.length > 0) {
				client.action(data.channel, message);
			}
		}
		else {
			client.say(data.channel, data.message);
		}
	});

_s is the http://epeli.github.io/underscore.string underscore string library, extremely useful.

**Comment by Schmoopiie** [comment]
Fixed, will bump the module version this weekend.

Thanks!
