### ISSUE TITLE
Join/Part events doesnt work

### ISSUE THREAD

**Issue by larzuk91** [twitch-irc/twitch-irc#77]
Hi, I was trying to catch Join and Part event so I can keep a track of every user watching my stream but looks like those events has been removed from twitch's API.

Is there any workaround to keep catching those events ?

Thanks in advance.

**Comment by Schmoopiie** [comment]
If using ``TWITCHCLIENT 1`` doesn't work for you, I recommend to use the internal Twitch API to keep a track of who is watching a stream. There is an example available in the documentation [here](http://www.schmoopiie.com/docs/twitch-irc/Examples/Query%20Twitch%20Internal%20API).

**Comment by larzuk91** [comment]
Hey Schmoopiie, thanks for your fast answer

What I'm really trying to do is to track time watched for every user in the stream. I thought in doing the way you said but, I would have to process viewers list every minute or so, in order to keep it clean and accurate.

I find this very overprocessing and it may consume a lot of server resources, that's why I feel like I need those events. I dont know how you see it

**Comment by Schmoopiie** [comment]
This [post](http://discuss.dev.twitch.tv/t/irc-v3-the-future/1121) explains why I do not recommend the use of ``TWITCHCLIENT 1`` when you want to track viewers. He said: "Keep in mind that we plan to deprecate the existing protocols (aka TWITCHCLIENT), but have no ETA when old protocol versions will no longer be supported." - Of couse we don't know when it will be deprecated but I'm not taking any chances.

I will try using tc 1 tomorrow to see if something is wrong with it, will keep you updated here.

Thanks!

**Comment by larzuk91** [comment]
Thanks again Schmoopiie. I have been trying with channels with less than 1k viewers

**Comment by Schmoopiie** [comment]
Are you using tc: 1 in your options ? By default the module is using TWITCHCLIENT 4 which is not what you want if you want to catch all the joins and parts. If you are not sure, check the [configuration options](http://www.schmoopiie.com/docs/twitch-irc/Configuration).

**Comment by Schmoopiie** [comment]
I just tried the module to get joins and parts and it is working properly. I guess you are not using ``TWITCHCLIENT 1``, hence why you can only see the client joining/leaving a channel. I am providing you the piece of code I used to investigate your issue.. Keep in mind that joins and parts are delayed and sent in batch.

```javascript
var irc = require('twitch-irc');

var clientOptions = {
    options: {
        debug: true,
        debugIgnore: ['ping', 'action', 'chat'],
        tc: 1
    },
    identity: {
        username: 'Your-username',
        password: 'oauth:token'
    },
    channels: ['lirik']
};

var client = new irc.client(clientOptions);

client.connect();

client.addListener('join', function (channel, username) {
    console.log('[JOIN] ' + channel + '> ' + username);
});

client.addListener('part', function (channel, username) {
    console.log('[PART] ' + channel + '> ' + username);
});
```

**Comment by larzuk91** [comment]
Hi there,

I was using default option, changed it to 1 and it worked. Thank you for your time.
