### ISSUE TITLE
Looks like host_target no longer exists..

### ISSUE THREAD

**Issue by Schmoopiie** [twitch-irc/twitch-irc#78]
When joining a channel, the module is using http://chatdepot.twitch.tv/rooms/CHANNEL/host_target to know if the channel is hosting another channel, however this endpoint no longer exists. Knowing this could happen, this will cause no issues when joining a channel, but the host event will be ignored.

What we have found so far:
- We have to get the ID of the channel using https://api.twitch.tv/kraken/channels/CHANNEL
- Make a request to http://tmi.twitch.tv/hosts?include_logins=1&host=ID (change ID)

We will wait before releasing any updates as there might be more changes..

**Comment by celluj34** [comment]
Why they can't just expand their REST api is beyond me. Stuff everything into the Channels api and be done with it.

**Comment by Schmoopiie** [comment]
Fixed, will bump the module version this weekend.

Thanks!
