### ISSUE TITLE
Add display-name to user object

### ISSUE THREAD

**Issue by bryanveloso** [twitch-irc/twitch-irc#81]
Heard word that chat responses now include `display-name`. 
It'd be great to have that in the `user` object for chat and action events!

**Comment by celluj34** [comment]
For twitch, wouldn't the username and display name the same thing?

**Comment by bryanveloso** [comment]
Users can customize capitalization in their settings, which is saved as `display-name`.

**Comment by Schmoopiie** [comment]
Thanks @bryanveloso, didn't notice this change! :smile:

Will push to NPM later though. (this weekend or the next one)
