### ISSUE TITLE
Responding to PING with PONG

### ISSUE THREAD

**Issue by demonicpagan** [twitch-irc/twitch-irc#90]
I'm a bit lost as to how to respond to a PING response using this API. Could some clarification or an example be provided?

**Comment by Schmoopiie** [comment]
You don't need to. The module does it automatically. Only use the [PING Command](http://www.schmoopiie.com/docs/twitch-irc/Commands/Ping) if for some reasons you need to check the latency with the [PONG Event](http://www.schmoopiie.com/docs/twitch-irc/Events/Pong).
