### ISSUE TITLE
What is the cause of this?

### ISSUE THREAD

**Issue by demonicpagan** [twitch-irc/twitch-irc#93]
I opened a public Gist with full (I hope, anyway) explanation of what I am attempting and what I am seeing. I cannot figure out what is going on and why.

https://gist.github.com/demonicpagan/9233ab9aab691302f998

**Comment by demonicpagan** [comment]
Ok, I figured out the repeating issue was do to having an addListener on chat in my commands being called. Still can't figure out why the user I'm trying to ban isn't being added to the channels ban list

**Comment by Schmoopiie** [comment]
Sorry for late response,

Good to see you fixed your problem. Be careful when using require because Node.JS will keep it in memory. If the ban isn't added to your ban list, it might just be a Twitch issue, try to ban someone yourself and see if it really work.

**Comment by demonicpagan** [comment]
using .ban playeringimfree in my channel, i get a response from Twitch in channel saying that the user is already banned (even though they still don't show up in my banned chatters list under Channel & Videos settings).

7:07 Demonicpagan: .ban playeringimfree
7:07 playeringimfree is already banned in this room.

**Comment by Schmoopiie** [comment]
Okay so that is a bug with Twitch, I will report your issue to the Staff and hopefully it will get fixed asap.
