### ISSUE TITLE
Notice of upcoming changes: deprecating the TWITCHCLIENT command

### ISSUE THREAD

**Issue by Fasani** [twitch-irc/twitch-irc#96]
I assume you all know about this?

http://discuss.dev.twitch.tv/t/notice-of-upcoming-changes-deprecating-the-twitchclient-command/2270

This is a heads up if not...

**Comment by celluj34** [comment]
Awesome. Hopefully this makes things easier in the long run. Link to new
docs:
https://github.com/justintv/Twitch-API/blob/master/chat/capabilities.md

**Comment by Schmoopiie** [comment]
Thanks guys, I will add this to the Roadmap!
