### ISSUE TITLE
display-name sometimes missing

### ISSUE THREAD

**Issue by mccxiv** [twitch-irc/twitch-irc#99]
For a small percentage of users, the display-name properly is returning the boolean value true instead of a string. It happens on a user by user basis, not randomly.

Possibly related? http://discuss.dev.twitch.tv/t/display-name-not-reliable/2277 Although I haven't personally seen this happen before today.

I'm adding a check in my code but if it keeps happening then maybe the library should do it or at least be documented.

**Comment by Schmoopiie** [comment]
Hello @mccxiv!

It is related to this and we are using the irc-message module which is returning a boolean value (always true) when a tag is empty / null. In the next version of twitch-irc, we will return only what is being sent by Twitch + some of our custom tags. ``display-name`` is not part of our custom tags so it will be omitted if Twitch is omitting it sometimes, so you will need to check if it is ``undefined`` before using it.
